version: '3'

services:
  postgres:
    container_name: typeORMPlayV0
    image: postgres:14.5
    ports:
      - 5444:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: typeorm_v0
